[project]
name = "default"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "a5chin" }
]
dependencies = [
    "stateless>=0.5.2",
]
readme = "README.md"
requires-python = ">= 3.12"

[tool.rye]
managed = true
dev-dependencies = [
    "pytest>=8.3.2",
    "pre-commit>=3.8.0",
    "ruff>=0.5.5",
]
